before_script:
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm whoami
  - npm install --progress=false

stages:
  - lint
  - build
  - test
  - publish
  - deploy

image: node:10

lint source:
  stage: lint
  script:
  - npm run lint

build app:
  stage: build
  script:
  - npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - dist

unit test:
  stage: test
  script:
  - npm run test:unit

publish app:
  stage: publish
  script:
  - npm publish --access private

deploy staging:
  stage: deploy
  script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-add <(echo "$SSH_PRIVATE_DSA_KEY")
  - ssh -p22 gitlab-runner@10.200.1.107 "cd /var/www/zam-wallet"
  - ssh -p22 gitlab-runner@10.200.1.107 "npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}"
  - ssh -p22 gitlab-runner@10.200.1.107 "npm whoami"
  - ssh -p22 gitlab-runner@10.200.1.107 "npm i @zamzamtech/wallet@latest"