before_script:
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm whoami
  - npm install --progress=false

stages:
  - lint
  - build
  - test
  - publish
  - deploy

image: node:10

lint source:
  stage: lint
  script:
  - npm run lint

build app:
  stage: build
  script:
  - npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - dist

unit test:
  stage: test
  script:
  - npm run test:unit

publish app:
  stage: publish
  script:
  - npm publish --access private

deploy staging:
  stage: deploy
  script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_DSA_KEY" | tr -d '\r' > ~/.ssh/id_dsa
  - chmod 700 ~/.ssh/id_dsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_dsa
  - ssh-keyscan -H 'git.zam.io' >> ~/.ssh/known_hosts
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm whoami
  - npm install @zamzamtech/wallet@latest