before_script:
#  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm set registry http://npm.zam.io:4873
  - npm whoami

stages:
  - lint
  - build
  - test
  - publish
  - deploy

image: node:10

lint source:
  stage: lint
  script:
    - npm install --progress=false
    - npm run lint

build app staging:
  stage: build
  environment:
    name: staging
  script:
    - export NODE_ENV=staging
    - npm install --progress=false
    - VUE_APP_ROOT_API=$VUE_APP_ROOT_API_STAGING npm run build
    - node packageVersionLabeling.js
  artifacts:
    expire_in: 1 day
    paths:
      - dist
  only:
    - develop

build app testing:
  stage: build
  environment:
    name: testing
  script:
    - export NODE_ENV=testing
    - npm install --progress=false
    - VUE_APP_ROOT_API=$VUE_APP_ROOT_API_TESTING npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - testing

build app production:
  stage: build
  environment:
    name: production
  script:
    - export NODE_ENV=production
    - npm install --progress=false
    - VUE_APP_ROOT_API=$VUE_APP_ROOT_API_PRODUCTION npm run build
  artifacts:
    expire_in: 1 month
    paths:
      - dist
  only:
    - master

unit test:
  stage: test
  script:
  - npm install --progress=false
  - npm run test:unit

publish app staging:
  stage: publish
  script:
    - export NODE_ENV=staging
    - npm publish --registry http://npm.zam.io:4873
  only:
    - develop

publish app testing:
  stage: publish
  script:
    - export NODE_ENV=testing
    - npm publish --registry http://npm.zam.io:4873
  only:
    - testing

publish app production:
  stage: publish
  script:
    - export NODE_ENV=production
    - npm publish --registry http://npm.zam.io:4873
  only:
    - master

deploy staging:
  stage: deploy
  environment:
    name: staging
  script:
    - echo "$SSH_PRIVATE_DSA_KEY" > id_dsa
    - chmod 600 id_dsa
    - cat id_dsa
    - ssh -o StrictHostKeyChecking=no -i id_dsa zam@10.200.1.107 "cd /var/www/zam-wallet && npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN} && npm whoami && npm i @zamzamtech/wallet@latest"
    - rm id_dsa
  only:
    - develop