build site:
  image: node:10
  stage: build
  script:
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm whoami
  - npm install --progress=false
  - npm run build
  artifacts:
    expire_in: 1 week
    paths:
    - dist

#unit test:
#  image: node:10
#  stage: test
#  script:
#  - npm install --progress=false
#  - npm run test:unit

deploy:
  image: alpine
  stage: deploy
  script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_DSA_KEY" | tr -d '\r' > ~/.ssh/id_dsa
  - chmod 700 ~/.ssh/id_dsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_dsa
  - ssh-keyscan -H 'git.zam.io' >> ~/.ssh/known_hosts
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - npm whoami
  - npm install @zamzamtech/wallet@latest